### PR TITLE
Flightsql connection working

### PR DESCRIPTION
**Pull request by matthewmturner**
Adds a new tab for FlightSQL client

image

### CODE REVIEW

**Comment by alamb** [comment]
I played around a bit with the code and the ui -- it took me some time getting used to it (kind of vim-like bindings) but once I got the hang of it, it was quite cool

Some feedback is:
1. I found it very hard to figure out how to quit (especially once I got into the logs pane)  -- I tried `Ctrl-C`, `Ctrl-D`, and `q` which did not work
2. I also kept trying to want to get some sort of help by typing `h` or `?` but neither of those keys did what I expected

**Review by alamb — APPROVED** [review]

**Comment by matthewmturner** [comment]
ah i jsut got this completely working this morning, was about to push up some more changes.  but ill just do another pr.

but i agree on the point regarding quiting and keys in general.  im still giving that some thought.

**Comment by matthewmturner** [comment]
@alamb it also has some key handling improvements.

**Comment by matthewmturner** [comment]
@alamb no problem at all. its definitely very fast moving, i think the next pr im about to do has some pretty good improvements and flightsql is fully working now.

regarding point 1 did you try setting ddl in `~/.datafusion/.datafusionrc`

there is logic [here](https://github.com/datafusion-contrib/datafusion-tui/blob/main/src/app/handlers/mod.rs#L153-L165) for that which iterates over all queries in it

**Comment by alamb** [comment]
> @alamb no problem at all. its definitely very fast moving, i think the next pr im about to do has some pretty good improvements and flightsql is fully working now.
> 
> regarding point 1 did you try setting ddl in `~/.datafusion/.datafusionrc`

I did not

> there is logic [here](https://github.com/datafusion-contrib/datafusion-tui/blob/main/src/app/handlers/mod.rs#L153-L165) for that which iterates over all queries in it

Nice

What I am (not so) secretly hoping, is to create some sort of file based catalog format (similar to the duckdb .db format) that can have DDL but also more crazy things like the contents of parquet metadata from remote object stores

But I don't even really have time to do what I want today, let alone this other cool stuff. Some day

**Comment by matthewmturner** [comment]
@alamb actually after seeing the diff i think the key handling improvements were already there. but i just merged my latest changes.  the next thing i wanted to get working was an s3 feature so i could have DDL that uses that.

also just making sure you saw - there is some help on the bottom of the screen that says some key bindings

**Comment by matthewmturner** [comment]
> What I am (not so) secretly hoping, is to create some sort of file based catalog format (similar to the duckdb .db format) that can have DDL but also more crazy things like the contents of parquet metadata from remote object stores

That would be very cool and i think could bring a lot of value to the ecosystem.  did you have any preliminary thoughts on the metadata part?

we could definitely add an experimental feature for exploring that topic.

i do also plan on adding some catalog / schema exploration capabilities so could be related to that.

**Pull request merged**
