### PR TITLE
Page up/down and move execution to normal mode

### PR DESCRIPTION
**Pull request by matthewmturner**
@seryj FYI adding page up/down and i did try shift+enter but im having trouble with it(the `KeyModifier::SHIFT` isnt being recognized for some reason).  will need to come back to it or table for now.

### CODE REVIEW

**Comment by matthewmturner** [comment]
Perhaps its unsupported by crossterm https://github.com/crossterm-rs/crossterm/issues/400

**Comment by seryj** [comment]
For me, it's an absolutely acceptable solution. I mean, yes, it does not align with other tools... but you know: how many other terminal UI tools for data analysis do exist?! At least out off my head I can call exactly zero. Having such a tool is really a big gain and such small differences really do not play a big role. 
At least, I see it this way. And if at some point people really start using this tool extensively, there will be solution for other key bindings.

**Comment by matthewmturner** [comment]
Man even alt enter is giving me lots of issues.  Been digging through other peoples hacks but still not getting the key combination recognized.  i think i will just have execution via normal mode for now and come back to this.

**Comment by matthewmturner** [comment]
well i think i got a baseline interface down to execute with enter from normal mode.  not ideal but i think good enough for 0.1.  i really want to get alt+enter or something of the sort supported though in the next release.

**Pull request merged**
