### PR TITLE
Remove bigtable

### PR DESCRIPTION
**Pull request by matthewmturner**

### CODE REVIEW

**Comment by jychen7** [comment]
just curious the reason to remove bigtable.
I do understand it is less maintenance and not a typical object store scenario

**Comment by matthewmturner** [comment]
@jychen7 sry I did that without giving you heads up - I was short on time. i created a dedicated bigtable branch for it as I was upgrading to latest datafusion and bigtable wasn't compatible. Would you be able to upgrade it to datafusion 8.0 and then I can add it back?

**Comment by jychen7** [comment]
you are correct, that makes sense. I will create a issue to upgrade to datafusion 8. I remember it introduce data_access crate.

no need sorry, I myself not use datafusion with bigtable recently, I could raise PR to add back to tui after upgrade and if still have the need

**Comment by matthewmturner** [comment]
@jychen7 fyi this is branch https://github.com/datafusion-contrib/datafusion-tui/tree/bigtable

**Comment by matthewmturner** [comment]
@jychen7 any chance you could do that in the coming days? I'm hoping to do a release soon.

**Comment by jychen7** [comment]
@matthewmturner I could try, but do not wait it for release, release at your own schedule :D

**Comment by matthewmturner** [comment]
@jychen7 Ok - thanks. I can do another release once added if it would help you.

**Pull request merged**
